version: 2.1
orbs:
  android: circleci/android@2.5.0
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: cimg/android:2024.01
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum  "composeApp/build.gradle.kts" }}
      - run:
          name: Create local.properties
          command: printf 'gemini_api_key=%s\natlas_app_id=%s\natlas_base_url=%s' \
            $gemini_api_key $atlas_app_id $atlas_base_url > local.properties
      - run:
          name: Decode Android key store
          command: echo $ETONG_KEYSTORE_BASE64 | base64 -d | tee etong_signature
      - run:
          name: Create keystore.properties
          command: printf 'keyAlias=%s\nkeyPassword=%s\nstoreFile=%s\nstorePassword=%s' \ 
            $KEY_ALIAS $KEY_PASSWORD $RELEASE_KEYSTORE $STORE_PASSWORD > keystore.properties
      - run:
          name: Create Google Play key
          command: echo $GOOGLE_PLAY_KEY > fastlane/etong-gcloud-project-47e075538758.json

      # Generate apk
      - run:
          name: Build Release AAB
          command: ./gradlew composeApp:bundleRelease --stacktrace
      - store_artifacts:
          path: composeApp/build/outputs/bundle/
          destination: apks/

      - run:
          name: Install Fastlane
          command: sudo gem install fastlane

      - run:
          name: Uploading an AAB to Play Store Internal
          command: fastlane internal_playstore
#          command: fastlane supply --aab composeApp/build/outputs/bundle/release/composeApp-release.aab

      # run tests!
#      - run: ./gradlew test